import { ProjectMeta } from "@/components/ui/ProjectCard";

export const projects: ProjectMeta[] = [
  {
    slug: "brand-film-01",
    title: "Brand Film — Horizon",
    description: "Cinematic brand narrative for a lifestyle startup.",
    category: "Video Editing",
    year: "2026",
    tools: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
    aspectRatio: "video",
    videoUrl: "https://drive.google.com/file/d/1WrG1n-ApPOGsmi90w7honURwK38kjZZD/preview",
  },
  {
    slug: "motion-reel-q1",
    title: "Motion Reel — Q1 2026",
    description: "A collection of motion design work from Q1.",
    category: "Motion Design",
    year: "2026",
    tools: ["After Effects", "Cinema 4D"],
    aspectRatio: "video",
    videoUrl: "https://drive.google.com/file/d/1wT2tok2mXnPo9ewFf_WihmTHCQy2_dpW/preview",
  },
  {
    slug: "product-launch",
    title: "Product Launch — Nova",
    description: "Full-service edit and color grade for a product launch.",
    category: "Video Editing",
    year: "2025",
    tools: ["Premiere Pro", "DaVinci Resolve"],
    aspectRatio: "video",
    videoUrl: "https://drive.google.com/file/d/18lXCuJL85S5zppRKVQaqqnXywJWkX4y2/preview",
  },
  {
    slug: "identity-design",
    title: "Visual Identity — Pulsar",
    description: "Static and animated brand identity system.",
    category: "Design",
    year: "2025",
    tools: ["Figma", "After Effects"],
    aspectRatio: "video",
    videoUrl: "https://drive.google.com/file/d/1ZH5MQrlh-sGYpJCslG8N6BdjyD4LOyKO/preview",
  },
  {
    slug: "documentary-cut",
    title: "Documentary — Roots",
    description: "Long-form narrative documentary edit.",
    category: "Video Editing",
    year: "2025",
    tools: ["Premiere Pro", "DaVinci Resolve"],
    aspectRatio: "video",
    videoUrl: "https://drive.google.com/file/d/12TKajueOKJenTDIRlpc709Az2-pGlcid/preview",
  },
  {
    slug: "social-campaign",
    title: "Social Campaign — Bloom",
    description: "Short-form video series for social media.",
    category: "Motion Design",
    year: "2024",
    tools: ["After Effects", "Premiere Pro"],
    aspectRatio: "video",
    videoUrl: "https://drive.google.com/file/d/1Oq2kKpkuNLS0M1902HoMg9hoX7Whl-gh/preview",
  },
];
